
#define MAC_LOGNOT(n) MAC_LOGNOT8(MAC_TO_INT(n))
#define MAC_LOGNOT0(n) 0

#define MAC_LOGNOT1(n) MAC_ADD(MAC_MUL(MAC_LOGNOT0(MAC_DIV(n, 2)), 2), MAC_NOT(MAC_MOD(n, 2)))
#define MAC_LOGNOT2(n) MAC_ADD(MAC_MUL(MAC_LOGNOT1(MAC_DIV(n, 2)), 2), MAC_NOT(MAC_MOD(n, 2)))
#define MAC_LOGNOT3(n) MAC_ADD(MAC_MUL(MAC_LOGNOT2(MAC_DIV(n, 2)), 2), MAC_NOT(MAC_MOD(n, 2)))
#define MAC_LOGNOT4(n) MAC_ADD(MAC_MUL(MAC_LOGNOT3(MAC_DIV(n, 2)), 2), MAC_NOT(MAC_MOD(n, 2)))
#define MAC_LOGNOT5(n) MAC_ADD(MAC_MUL(MAC_LOGNOT4(MAC_DIV(n, 2)), 2), MAC_NOT(MAC_MOD(n, 2)))
#define MAC_LOGNOT6(n) MAC_ADD(MAC_MUL(MAC_LOGNOT5(MAC_DIV(n, 2)), 2), MAC_NOT(MAC_MOD(n, 2)))
#define MAC_LOGNOT7(n) MAC_ADD(MAC_MUL(MAC_LOGNOT6(MAC_DIV(n, 2)), 2), MAC_NOT(MAC_MOD(n, 2)))
#define MAC_LOGNOT8(n) MAC_ADD(MAC_MUL(MAC_LOGNOT7(MAC_DIV(n, 2)), 2), MAC_NOT(MAC_MOD(n, 2)))
