#define MAC_GREATER(a, b) MAC_CONCAT(MAC_GREATER, MAC_CONCAT(MAC_BOOL(MAC_SUB(a, b)), MAC_BOOL(MAC_SUB(b, a))))
#define MAC_GREATER00 0
#define MAC_GREATER10 1
#define MAC_GREATER01 0
#define MAC_GREATER11 0
