
#define MAC_LOGOR(a, b) MAC_LOGOR8(MAC_TO_INT(a), MAC_TO_INT(b))
#define MAC_LOGORBIT00 0
#define MAC_LOGORBIT10 1
#define MAC_LOGORBIT01 1
#define MAC_LOGORBIT11 1
#define MAC_LOGOR0(a, b) 0

#define MAC_LOGOR1(a, b) MAC_ADD(MAC_MUL(MAC_LOGOR0(MAC_DIV(a, 2), MAC_DIV(b, 2)), 2), MAC_CONCAT(MAC_LOGORBIT, MAC_CONCAT(MAC_MOD(a, 2), MAC_MOD(b, 2))))
#define MAC_LOGOR2(a, b) MAC_ADD(MAC_MUL(MAC_LOGOR1(MAC_DIV(a, 2), MAC_DIV(b, 2)), 2), MAC_CONCAT(MAC_LOGORBIT, MAC_CONCAT(MAC_MOD(a, 2), MAC_MOD(b, 2))))
#define MAC_LOGOR3(a, b) MAC_ADD(MAC_MUL(MAC_LOGOR2(MAC_DIV(a, 2), MAC_DIV(b, 2)), 2), MAC_CONCAT(MAC_LOGORBIT, MAC_CONCAT(MAC_MOD(a, 2), MAC_MOD(b, 2))))
#define MAC_LOGOR4(a, b) MAC_ADD(MAC_MUL(MAC_LOGOR3(MAC_DIV(a, 2), MAC_DIV(b, 2)), 2), MAC_CONCAT(MAC_LOGORBIT, MAC_CONCAT(MAC_MOD(a, 2), MAC_MOD(b, 2))))
#define MAC_LOGOR5(a, b) MAC_ADD(MAC_MUL(MAC_LOGOR4(MAC_DIV(a, 2), MAC_DIV(b, 2)), 2), MAC_CONCAT(MAC_LOGORBIT, MAC_CONCAT(MAC_MOD(a, 2), MAC_MOD(b, 2))))
#define MAC_LOGOR6(a, b) MAC_ADD(MAC_MUL(MAC_LOGOR5(MAC_DIV(a, 2), MAC_DIV(b, 2)), 2), MAC_CONCAT(MAC_LOGORBIT, MAC_CONCAT(MAC_MOD(a, 2), MAC_MOD(b, 2))))
#define MAC_LOGOR7(a, b) MAC_ADD(MAC_MUL(MAC_LOGOR6(MAC_DIV(a, 2), MAC_DIV(b, 2)), 2), MAC_CONCAT(MAC_LOGORBIT, MAC_CONCAT(MAC_MOD(a, 2), MAC_MOD(b, 2))))
#define MAC_LOGOR8(a, b) MAC_ADD(MAC_MUL(MAC_LOGOR7(MAC_DIV(a, 2), MAC_DIV(b, 2)), 2), MAC_CONCAT(MAC_LOGORBIT, MAC_CONCAT(MAC_MOD(a, 2), MAC_MOD(b, 2))))
