#define MAC_LESSER_OR_EQUAL(a, b) MAC_CONCAT(MAC_LESSER_OR_EQUAL, MAC_CONCAT(MAC_BOOL(MAC_SUB(a, b)), MAC_BOOL(MAC_SUB(b, a))))
#define MAC_LESSER_OR_EQUAL00 1
#define MAC_LESSER_OR_EQUAL10 0
#define MAC_LESSER_OR_EQUAL01 1
#define MAC_LESSER_OR_EQUAL11 0
