#define MAC_LESSER(a, b) MAC_CONCAT(MAC_LESSER, MAC_CONCAT(MAC_BOOL(MAC_SUB(a, b)), MAC_BOOL(MAC_SUB(b, a))))
#define MAC_LESSER00 0
#define MAC_LESSER10 0
#define MAC_LESSER01 1
#define MAC_LESSER11 0
