#define MAC_UNEQUAL(a, b) MAC_CONCAT(MAC_UNEQUAL, MAC_CONCAT(MAC_BOOL(MAC_SUB(a, b)), MAC_BOOL(MAC_SUB(b, a))))
#define MAC_UNEQUAL00 0
#define MAC_UNEQUAL10 1
#define MAC_UNEQUAL01 1
#define MAC_UNEQUAL11 0
